---
title: MZ
timezone: UTC
collections:
  courses:
    title: Courses
    output: true
    permalink: "/courses/:name/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: courses
  values:
    layout: course
    permalink: "/courses/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
url: http://example.com
baseurl: ''
description: MZed is the leading online education platform for filmmakers and photographers.
markdown: kramdown
permalink: pretty
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor
- README.md
plugins:
- jekyll-sitemap
- jekyll-seo-tag
siteleaf:
  build_command: bundle exec jekyll build
  serve_command: bundle exec jekyll serve

# SCSS Configuration
sass:
  sass_dir: _sass
  style: compressed
